// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzagithcqoiwybjljgmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6YWdpdGhjcW9pd3liamxqZ21rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3Njg5NDksImV4cCI6MjA2NjM0NDk0OX0.EyMBKrw74FrDiWMH9xKJXUFVNT7e28JDlZIIeYeg3F0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);